name: CD
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: sbt

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libidn2-dev libcurl4-openssl-dev

    - name: Setup sbt Launcher
      uses: sbt/setup-sbt@v1
      with:
        sbt-runner-version: 1.10.6

    - name: Build Binary
      run: sbt nativeLink

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: metakultur-binary
        path: target/scala-3.3.5/metakultur

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/scala-3.3.5/metakultur
      env:
        GITHUB_TOKEN: ${{ secrets.METAKULTUR_GITHUB_TOKEN }}
